from .command_conformance import (
    CommandConformanceCase,
    CommandConformanceOptions,
    create_command_conformance_cases,
)
from .command_harness import (
    NO_STDIN,
    CreateTestCommandContextOptions,
    RunRegisteredCommandOptions,
    RunRegisteredCommandResult,
    create_test_command_context,
    create_test_command_registry,
    get_registered_command,
    run_registered_command,
    stdin_text,
    stdout_text,
)
from .adapters import DemoFetch, DemoSearch, DemoSearchDocument
from .assert_scenario import AssertionResult, assert_scenario
from .demo_fixtures import (
    ACME_ACCOUNT_TEXT,
    APP_LOG_TEXT,
    DEFAULT_CONFIG_TEXT,
    DEMO_FETCH_RESOURCES,
    DEMO_FILES,
    DEMO_MEMORY_ENTRIES,
    DEMO_SEARCH_DOCS,
    LOGO_PNG_BYTES,
    PROD_CONFIG_TEXT,
    QBR_DRAFT_TEXT,
    TODO_TEXT,
    generate_large_log,
    seed_demo_memory,
    seed_demo_vfs,
)
from .demo_runtime import DemoRuntimeOptions, build_demo_runtime, seed_memory, seed_vfs
from .oracle_runner import OracleStepTrace, OracleTrace, run_oracle
from .scenario import (
    AssertionSpec,
    FileAssertionSpec,
    MemoryAssertionSpec,
    OracleCommandSpec,
    ScenarioCategory,
    ScenarioPromptVariant,
    ScenarioSpec,
    TextAssertionSpec,
    TraceAssertionSpec,
    TraceStepAssertionSpec,
    WorldSpec,
)
from .world_builder import build_world

__all__ = [
    "ACME_ACCOUNT_TEXT",
    "APP_LOG_TEXT",
    "AssertionResult",
    "AssertionSpec",
    "CommandConformanceCase",
    "CommandConformanceOptions",
    "CreateTestCommandContextOptions",
    "DEFAULT_CONFIG_TEXT",
    "DEMO_FETCH_RESOURCES",
    "DEMO_FILES",
    "DEMO_MEMORY_ENTRIES",
    "DEMO_SEARCH_DOCS",
    "DemoFetch",
    "DemoRuntimeOptions",
    "DemoSearch",
    "DemoSearchDocument",
    "FileAssertionSpec",
    "LOGO_PNG_BYTES",
    "MemoryAssertionSpec",
    "NO_STDIN",
    "OracleCommandSpec",
    "OracleStepTrace",
    "OracleTrace",
    "PROD_CONFIG_TEXT",
    "QBR_DRAFT_TEXT",
    "RunRegisteredCommandOptions",
    "RunRegisteredCommandResult",
    "ScenarioCategory",
    "ScenarioPromptVariant",
    "ScenarioSpec",
    "TODO_TEXT",
    "TextAssertionSpec",
    "TraceAssertionSpec",
    "TraceStepAssertionSpec",
    "WorldSpec",
    "assert_scenario",
    "create_command_conformance_cases",
    "create_test_command_context",
    "create_test_command_registry",
    "build_demo_runtime",
    "build_world",
    "generate_large_log",
    "get_registered_command",
    "run_oracle",
    "run_registered_command",
    "seed_demo_memory",
    "seed_demo_vfs",
    "seed_memory",
    "seed_vfs",
    "stdin_text",
    "stdout_text",
]
