export type ExampleTier = 'quickstart' | 'recipe' | 'app' | 'reference';
export type ExampleRuntime = 'node' | 'browser' | 'http' | 'live';

export interface ExampleManifestEntry {
  slug: string;
  title: string;
  tier: ExampleTier;
  runtime: ExampleRuntime;
  summary: string;
  modulePath: string;
  sourcePath: string;
  runCommand: string;
  deterministic: boolean;
  requiresEnv: boolean;
  smokeTest: boolean;
  smokeArgs?: readonly string[];
  surfaces: readonly string[];
  tags: readonly string[];
}

export const exampleManifest: readonly ExampleManifestEntry[] = Object.freeze([
  {
    slug: 'quickstart-node-basic',
    title: 'Quickstart: Node runtime',
    tier: 'quickstart',
    runtime: 'node',
    summary: 'Create a basic runtime, execute commands, and build the tool definition.',
    modulePath: './quickstarts/node-basic.js',
    sourcePath: 'examples/quickstarts/node-basic.ts',
    runCommand: 'npm run example -- quickstart-node-basic',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'NodeVFS', 'buildToolDefinition'],
    tags: ['quickstart', 'node', 'tool-definition'],
  },
  {
    slug: 'quickstart-readonly-preset',
    title: 'Quickstart: read-only preset',
    tier: 'quickstart',
    runtime: 'node',
    summary: 'Start with a safe read-only command set using a built-in preset.',
    modulePath: './quickstarts/readonly-preset.js',
    sourcePath: 'examples/quickstarts/readonly-preset.ts',
    runCommand: 'npm run example -- quickstart-readonly-preset',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'builtinCommands', 'MemoryVFS'],
    tags: ['quickstart', 'preset', 'read-only'],
  },
  {
    slug: 'quickstart-run-detailed',
    title: 'Quickstart: structured execution',
    tier: 'quickstart',
    runtime: 'node',
    summary: 'Inspect exit codes, traces, and presentation metadata with runDetailed().',
    modulePath: './quickstarts/run-detailed.js',
    sourcePath: 'examples/quickstarts/run-detailed.ts',
    runCommand: 'npm run example -- quickstart-run-detailed',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'runDetailed'],
    tags: ['quickstart', 'observability', 'trace'],
  },
  {
    slug: 'quickstart-custom-command',
    title: 'Quickstart: custom command',
    tier: 'quickstart',
    runtime: 'node',
    summary: 'Add one domain-specific command with the public extension helpers.',
    modulePath: './quickstarts/custom-command.js',
    sourcePath: 'examples/quickstarts/custom-command.ts',
    runCommand: 'npm run example:custom-command',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'one-tool/extensions'],
    tags: ['quickstart', 'custom-command', 'extensions'],
  },
  {
    slug: 'recipe-command-selection',
    title: 'Recipe: command selection',
    tier: 'recipe',
    runtime: 'node',
    summary: 'Compose presets, groups, exclusions, and custom-only runtimes.',
    modulePath: './recipes/command-selection.js',
    sourcePath: 'examples/recipes/command-selection.ts',
    runCommand: 'npm run example -- recipe-command-selection',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'one-tool/commands'],
    tags: ['recipe', 'registry', 'presets'],
  },
  {
    slug: 'recipe-command-overrides',
    title: 'Recipe: command overrides',
    tier: 'recipe',
    runtime: 'node',
    summary: 'Replace, unregister, and inject commands with a caller-owned registry.',
    modulePath: './recipes/command-overrides.js',
    sourcePath: 'examples/recipes/command-overrides.ts',
    runCommand: 'npm run example -- recipe-command-overrides',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'one-tool/commands'],
    tags: ['recipe', 'override', 'registry'],
  },
  {
    slug: 'recipe-extension-helpers',
    title: 'Recipe: extension helpers',
    tier: 'recipe',
    runtime: 'node',
    summary: 'Build a small command pack with the stable one-tool/extensions helpers.',
    modulePath: './recipes/extension-helpers.js',
    sourcePath: 'examples/recipes/extension-helpers.ts',
    runCommand: 'npm run example -- recipe-extension-helpers',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'one-tool/extensions'],
    tags: ['recipe', 'extensions', 'command-pack'],
  },
  {
    slug: 'recipe-testing-custom-commands',
    title: 'Recipe: testing custom commands',
    tier: 'recipe',
    runtime: 'node',
    summary: 'Use one-tool/testing for harnesses and metadata-driven conformance checks.',
    modulePath: './recipes/testing-custom-commands.js',
    sourcePath: 'examples/recipes/testing-custom-commands.ts',
    runCommand: 'npm run example -- recipe-testing-custom-commands',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool/testing'],
    tags: ['recipe', 'testing', 'conformance'],
  },
  {
    slug: 'recipe-browser-vfs',
    title: 'Recipe: BrowserVFS persistence',
    tier: 'recipe',
    runtime: 'browser',
    summary: 'Use BrowserVFS with IndexedDB persistence and reopen the same workspace.',
    modulePath: './recipes/browser-vfs.js',
    sourcePath: 'examples/recipes/browser-vfs.ts',
    runCommand: 'npm run example -- recipe-browser-vfs',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'one-tool/vfs/browser'],
    tags: ['recipe', 'browser', 'indexeddb'],
  },
  {
    slug: 'recipe-prompt-variants',
    title: 'Recipe: prompt variants',
    tier: 'recipe',
    runtime: 'node',
    summary: 'Compare full, minimal, and terse tool descriptions for evaluation work.',
    modulePath: './recipes/prompt-variants.js',
    sourcePath: 'examples/recipes/prompt-variants.ts',
    runCommand: 'npm run example -- recipe-prompt-variants',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'buildToolDefinition'],
    tags: ['recipe', 'prompt-variants', 'evaluation'],
  },
  {
    slug: 'recipe-overflow-and-binary',
    title: 'Recipe: overflow and binary handling',
    tier: 'recipe',
    runtime: 'node',
    summary: 'Inspect truncation and binary-guard metadata with runDetailed().',
    modulePath: './recipes/overflow-and-binary.js',
    sourcePath: 'examples/recipes/overflow-and-binary.ts',
    runCommand: 'npm run example -- recipe-overflow-and-binary',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'runDetailed', 'outputLimits'],
    tags: ['recipe', 'overflow', 'binary'],
  },
  {
    slug: 'recipe-scenario-testing',
    title: 'Recipe: scenario testing',
    tier: 'recipe',
    runtime: 'node',
    summary: 'Build a world, run a deterministic oracle, and assert the result.',
    modulePath: './recipes/scenario-testing.js',
    sourcePath: 'examples/recipes/scenario-testing.ts',
    runCommand: 'npm run example -- recipe-scenario-testing',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool/testing'],
    tags: ['recipe', 'scenario', 'oracle'],
  },
  {
    slug: 'app-incident-investigator',
    title: 'Application: incident investigator',
    tier: 'app',
    runtime: 'node',
    summary: 'Investigate logs, configs, and orders, then write an incident report.',
    modulePath: './apps/incident-investigator.js',
    sourcePath: 'examples/apps/incident-investigator.ts',
    runCommand: 'npm run example:incident-investigator',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'search', 'fetch', 'write'],
    tags: ['app', 'incident-response', 'reporting'],
  },
  {
    slug: 'app-support-desk',
    title: 'Application: support desk',
    tier: 'app',
    runtime: 'node',
    summary: 'Combine a custom ticket command with built-ins to work a support queue.',
    modulePath: './apps/support-desk.js',
    sourcePath: 'examples/apps/support-desk.ts',
    runCommand: 'npm run example -- app-support-desk',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'one-tool/extensions', 'memory'],
    tags: ['app', 'support', 'custom-command'],
  },
  {
    slug: 'app-knowledge-brief',
    title: 'Application: knowledge brief',
    tier: 'app',
    runtime: 'node',
    summary: 'Collect search hits, fetch structured records, and write a reusable brief.',
    modulePath: './apps/knowledge-brief.js',
    sourcePath: 'examples/apps/knowledge-brief.ts',
    runCommand: 'npm run example -- app-knowledge-brief',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'search', 'fetch', 'memory'],
    tags: ['app', 'briefing', 'knowledge'],
  },
  {
    slug: 'app-browser-notebook',
    title: 'Application: browser notebook',
    tier: 'app',
    runtime: 'browser',
    summary: 'Persist notes across sessions with BrowserVFS and a notebook-style workflow.',
    modulePath: './apps/browser-notebook.js',
    sourcePath: 'examples/apps/browser-notebook.ts',
    runCommand: 'npm run example -- app-browser-notebook',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    surfaces: ['one-tool', 'one-tool/vfs/browser'],
    tags: ['app', 'browser', 'notes'],
  },
  {
    slug: 'reference-demo-cli',
    title: 'Reference: seeded demo CLI',
    tier: 'reference',
    runtime: 'node',
    summary: 'Interactive seeded CLI with adapters, files, memory, and example commands.',
    modulePath: './reference/demo-cli.js',
    sourcePath: 'examples/reference/demo-cli.ts',
    runCommand: 'npm run demo',
    deterministic: true,
    requiresEnv: false,
    smokeTest: false,
    surfaces: ['one-tool', 'reference'],
    tags: ['reference', 'interactive', 'demo'],
  },
  {
    slug: 'reference-provider-agent',
    title: 'Reference: provider-backed agent',
    tier: 'reference',
    runtime: 'live',
    summary: 'Wire the runtime to a real model via Groq, OpenAI, or Anthropic compatibility endpoints.',
    modulePath: './reference/provider-agent.js',
    sourcePath: 'examples/reference/provider-agent.ts',
    runCommand: 'npm run agent',
    deterministic: false,
    requiresEnv: true,
    smokeTest: false,
    surfaces: ['one-tool', 'provider', 'tool-definition'],
    tags: ['reference', 'agent', 'live'],
  },
  {
    slug: 'reference-mcp-stdio',
    title: 'Reference: MCP stdio server',
    tier: 'reference',
    runtime: 'node',
    summary: 'Expose the runtime as a native MCP tool for Claude Code and other MCP clients.',
    modulePath: './reference/mcp-stdio.js',
    sourcePath: 'examples/reference/mcp-stdio.ts',
    runCommand: 'npm run example:mcp-stdio',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    smokeArgs: ['--self-test'],
    surfaces: ['one-tool/mcp', 'mcp', 'run'],
    tags: ['reference', 'mcp', 'stdio'],
  },
  {
    slug: 'reference-http-tool-endpoint',
    title: 'Reference: HTTP tool endpoint',
    tier: 'reference',
    runtime: 'http',
    summary: 'Expose the runtime through a minimal HTTP service for tool-calling agents.',
    modulePath: './reference/http-tool-endpoint.js',
    sourcePath: 'examples/reference/http-tool-endpoint.ts',
    runCommand: 'npm run example -- reference-http-tool-endpoint',
    deterministic: true,
    requiresEnv: false,
    smokeTest: true,
    smokeArgs: ['--self-test'],
    surfaces: ['one-tool', 'http', 'tool-definition'],
    tags: ['reference', 'http', 'server'],
  },
]);

export function getExampleBySlug(slug: string): ExampleManifestEntry | undefined {
  return exampleManifest.find(function (entry) {
    return entry.slug === slug;
  });
}

export function listExamplesByTier(tier: ExampleTier): ExampleManifestEntry[] {
  return exampleManifest.filter(function (entry) {
    return entry.tier === tier;
  });
}
