import type { ExampleDef } from './types';

export const examples: ExampleDef[] = [
  {
    id: '01-hello-world',
    title: 'Hello World',
    description: 'Create a runtime and run familiar commands like ls and cat.',
    covers: ['write', 'cat', 'stat', 'mkdir -p', 'ls', 'help'],
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/01-hello-world.ts',
    runtimeKind: 'empty',
    autoPlay: true,
    stepDelayMs: 700,
    steps: [
      { explanation: 'Write a file:', command: 'write /hello.txt "Hello from one-tool"' },
      { explanation: 'Read it back:', command: 'cat /hello.txt' },
      { explanation: 'Inspect its metadata:', command: 'stat /hello.txt' },
      {
        explanation: 'Create a nested directory and inspect it:',
        command: 'mkdir -p /reports/demo && ls -a /reports',
      },
      { explanation: 'List the root directory:', command: 'ls -a /' },
      { explanation: 'See all available commands:', command: 'help' },
    ],
  },
  {
    id: '02-custom-command',
    title: 'Custom Command',
    description: 'Add a custom command and compose it with built-in commands.',
    covers: ['help ticket', 'ticket lookup', 'ticket list --open', 'write', 'json get'],
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/02-custom-command.ts',
    runtimeKind: 'custom-command',
    autoPlay: true,
    stepDelayMs: 800,
    steps: [
      { explanation: 'Inspect the custom command contract:', command: 'help ticket' },
      {
        explanation: 'Look up a ticket and extract its status:',
        command: 'ticket lookup TICKET-123 | json get status',
      },
      {
        explanation: 'List only open tickets and trim the output:',
        command: 'ticket list --open | head -n 2',
      },
      {
        explanation: 'Write the ticket payload to the workspace:',
        command: 'ticket lookup TICKET-123 | write /reports/ticket-123.json',
      },
      {
        explanation: 'Read a nested field back from the saved JSON:',
        command: 'cat /reports/ticket-123.json | json get customer.email',
      },
    ],
  },
  {
    id: '03-readonly-agent',
    title: 'Read-Only Agent',
    description: 'Use the read-only preset for safe inspection workflows.',
    covers: ['cat', 'stat', 'find', 'sort', 'grep', 'read-only preset'],
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/03-readonly-agent.ts',
    runtimeKind: 'readOnly',
    autoPlay: true,
    stepDelayMs: 700,
    steps: [
      { explanation: 'Read commands work:', command: 'cat /logs/app.log' },
      { explanation: 'Inspect file metadata:', command: 'stat /logs/app.log' },
      { explanation: 'Recursive discovery still works:', command: 'find /logs -type f | sort' },
      { explanation: 'List files:', command: 'ls -a /' },
      { explanation: 'Search works:', command: 'grep -c ERROR /logs/app.log' },
      {
        explanation: 'Mutating commands are unavailable in the preset:',
        command: 'write /test.txt "should fail"',
      },
    ],
  },
  {
    id: '04-detailed-execution',
    title: 'Detailed Execution',
    description: 'Inspect structured execution results and command traces.',
    covers: ['find', 'sort', '|| fallback', 'grep -F', 'tail -n', 'runDetailed'],
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/04-detailed-execution.ts',
    runtimeKind: 'demo',
    executionKind: 'runDetailed',
    autoPlay: true,
    stepDelayMs: 900,
    steps: [
      {
        explanation: 'Inspect discovered config files through a pipeline:',
        command: 'find /config -type f -name "*.json" | sort',
      },
      {
        explanation: 'Chain with fallback:',
        command: 'cat /config/missing.json || cat /config/default.json',
      },
      {
        explanation: 'Mix quoted text, pipes, and filtering in one command line:',
        command: "echo '--- latest timeout ---' && cat /logs/app.log | grep -F timeout | tail -n 1",
      },
    ],
  },
  {
    id: '05-adapters',
    title: 'Search & Fetch Adapters',
    description: 'Use search and fetch adapters with the runtime.',
    covers: ['search', 'head', 'fetch', 'json get', 'write', 'memory search'],
    group: 'agent-workflows',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/05-adapters.ts',
    runtimeKind: 'demo',
    autoPlay: true,
    stepDelayMs: 850,
    steps: [
      {
        explanation: 'Search and narrow the results before reading more:',
        command: 'search refund timeout | head -n 1',
      },
      { explanation: 'Fetch structured data:', command: 'fetch order:123' },
      { explanation: 'Extract a nested field:', command: 'fetch order:123 | json get customer.email' },
      {
        explanation: 'Read structured guidance from a fetched knowledge-base document:',
        command: 'fetch kb://incidents/refund-timeout | json get guidance[0]',
      },
      {
        explanation: 'Search, persist, and verify the saved report in one flow:',
        command: 'search "refund timeout" | write /reports/refund.txt && cat /reports/refund.txt',
      },
      { explanation: 'Use the seeded working memory too:', command: 'memory search "refund"' },
    ],
  },
  {
    id: '06-browser-persistence',
    title: 'Browser Persistence',
    description: 'Use BrowserVFS for persistent browser storage.',
    covers: ['write', 'append', 'cat', 'stat', 'ls', 'BrowserVFS'],
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/06-browser-persistence.ts',
    runtimeKind: 'browser-persistence',
    autoPlay: true,
    stepDelayMs: 850,
    steps: [
      {
        explanation: 'Write a persistent file:',
        command: 'write /notes/persistent.txt "This survives reloads"',
      },
      {
        explanation: 'Append another line to the same file:',
        command: 'append /notes/persistent.txt "\nAnd this survives too"',
      },
      {
        explanation: 'Read it back. Reload the page and rerun this step to confirm persistence.',
        command: 'cat /notes/persistent.txt',
      },
      { explanation: 'Inspect the saved file metadata:', command: 'stat /notes/persistent.txt' },
      { explanation: 'List persistent files:', command: 'ls -a /notes' },
    ],
  },
  {
    id: '07-mcp-server',
    title: 'MCP Server',
    description: 'Expose the runtime as an MCP tool for Claude Code.',
    covers: ['serveStdioMcpServer', 'NodeVFS', 'Claude Code', 'run tool'],
    group: 'agent-workflows',
    browserRunnable: false,
    requiresApiKey: false,
    sourceFile: 'examples/07-mcp-server.ts',
  },
  {
    id: '08-llm-agent',
    title: 'LLM Agent',
    description:
      'Run the browser agent demo over the demo workspace with OpenRouter and the same command forms used in the other examples.',
    covers: ['OpenRouter', 'run(command)', 'search', 'fetch', 'find', 'write'],
    group: 'agent-workflows',
    browserRunnable: true,
    requiresApiKey: true,
    sourceFile: 'examples/08-llm-agent.ts',
    runtimeKind: 'demo',
    suggestedPrompts: [
      'Count the ERROR lines in /logs/app.log and tell me the total.',
      'Fetch order:123, tell me the customer email, and save it to /notes/email.txt.',
      'Search for refund timeout guidance and write a short summary to /reports/refund.txt.',
      'Find JSON config files, count them, and tell me how many there are.',
      'If /config/prod.json is missing, fall back to the default config and tell me the region.',
    ],
  },
];

export function getExample(id: string): ExampleDef | undefined {
  return examples.find((e) => e.id === id);
}
