import type { ExampleDef } from './types';

export const examples: ExampleDef[] = [
  {
    id: '01-hello-world',
    title: 'Hello World',
    description: 'Create a runtime and run basic commands.',
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/01-hello-world.ts',
    runtimeKind: 'empty',
    autoPlay: true,
    stepDelayMs: 700,
    steps: [
      { explanation: 'Write a file:', command: 'write /hello.txt "Hello from one-tool"' },
      { explanation: 'Read it back:', command: 'cat /hello.txt' },
      { explanation: 'List the root directory:', command: 'ls /' },
      { explanation: 'See all available commands:', command: 'help' },
    ],
  },
  {
    id: '02-custom-command',
    title: 'Custom Command',
    description: 'Add a custom command and compose it with built-in commands.',
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/02-custom-command.ts',
    runtimeKind: 'custom-command',
    autoPlay: true,
    stepDelayMs: 800,
    steps: [
      { explanation: 'List commands (custom ones show up too):', command: 'help' },
      {
        explanation: 'Look up a ticket and extract its status:',
        command: 'ticket lookup T-123 | json get status',
      },
      {
        explanation: 'Extract a nested field from the same ticket payload:',
        command: 'ticket lookup T-123 | json get owner.email',
      },
    ],
  },
  {
    id: '03-readonly-agent',
    title: 'Read-Only Agent',
    description: 'Use the read-only preset for safe inspection workflows.',
    group: 'agent-workflows',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/03-readonly-agent.ts',
    runtimeKind: 'readOnly',
    autoPlay: true,
    stepDelayMs: 700,
    steps: [
      { explanation: 'Read commands work:', command: 'cat /logs/app.log' },
      { explanation: 'List files:', command: 'ls /' },
      { explanation: 'Search works:', command: 'grep ERROR /logs/app.log' },
      {
        explanation: 'Mutating commands are unavailable in the preset:',
        command: 'write /test.txt "should fail"',
      },
    ],
  },
  {
    id: '04-detailed-execution',
    title: 'Detailed Execution',
    description: 'Inspect structured execution results and command traces.',
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/04-detailed-execution.ts',
    runtimeKind: 'demo',
    executionKind: 'runDetailed',
    autoPlay: true,
    stepDelayMs: 900,
    steps: [
      { explanation: 'Count errors in the log:', command: 'grep -c ERROR /logs/app.log' },
      {
        explanation: 'Chain with fallback:',
        command: 'cat /config/missing.json || cat /config/default.json',
      },
      {
        explanation: 'Pipeline with multiple stages:',
        command: 'cat /logs/app.log | grep timeout | tail -n 1',
      },
    ],
  },
  {
    id: '05-adapters',
    title: 'Search & Fetch Adapters',
    description: 'Use search and fetch adapters with the runtime.',
    group: 'agent-workflows',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/05-adapters.ts',
    runtimeKind: 'demo',
    autoPlay: true,
    stepDelayMs: 850,
    steps: [
      { explanation: 'Search the knowledge base:', command: 'search refund timeout' },
      { explanation: 'Fetch structured data:', command: 'fetch order:123' },
      { explanation: 'Extract a nested field:', command: 'fetch order:123 | json get customer.email' },
      {
        explanation: 'Save search results to a file:',
        command: 'search refund timeout | write /reports/refund.txt',
      },
      { explanation: 'Verify the saved file:', command: 'cat /reports/refund.txt' },
    ],
  },
  {
    id: '06-browser-persistence',
    title: 'Browser Persistence',
    description: 'Use BrowserVFS for persistent browser storage.',
    group: 'cli-capabilities',
    browserRunnable: true,
    requiresApiKey: false,
    sourceFile: 'examples/06-browser-persistence.ts',
    runtimeKind: 'browser-persistence',
    autoPlay: true,
    stepDelayMs: 850,
    steps: [
      {
        explanation: 'Write a persistent file:',
        command: 'write /notes/persistent.txt "This survives reloads"',
      },
      {
        explanation: 'Read it back. Reload the page and rerun this step to confirm persistence.',
        command: 'cat /notes/persistent.txt',
      },
      { explanation: 'List persistent files:', command: 'ls /notes' },
    ],
  },
  {
    id: '07-mcp-server',
    title: 'MCP Server',
    description: 'Expose the runtime as an MCP tool for Claude Code.',
    group: 'agent-workflows',
    browserRunnable: false,
    requiresApiKey: false,
    sourceFile: 'examples/07-mcp-server.ts',
  },
  {
    id: '08-llm-agent',
    title: 'LLM Agent',
    description: 'Run the browser agent demo over the demo workspace with OpenRouter.',
    group: 'agent-workflows',
    browserRunnable: true,
    requiresApiKey: true,
    sourceFile: 'examples/08-llm-agent.ts',
    runtimeKind: 'demo',
    suggestedPrompts: [
      'Count the ERROR lines in /logs/app.log and tell me the total.',
      'Fetch order:123, tell me the customer email, and save it to /notes/email.txt.',
      'Search for refund timeout guidance and write a short summary to /reports/refund.txt.',
      'If /config/prod.json is missing, fall back to the default config and tell me the region.',
    ],
  },
];

export function getExample(id: string): ExampleDef | undefined {
  return examples.find((e) => e.id === id);
}
