from __future__ import annotations

from .core import CommandContext, CommandHandler, CommandRegistry, CommandSpec, maybe_await
from .groups.adapters import adapter_commands, fetch, search
from .groups.data import calc, data_commands, json_command
from .groups.fs import append, cat, cp, diff, find, fs_commands, ls, mkdir, mv, rm, stat, write
from .groups.system import help_command, memory, system_commands
from .groups.text import echo, grep, head, sed, sort, tail, text_commands, tr, uniq, wc
from .register import (
    BuiltinCommandGroupName,
    BuiltinCommandPresetName,
    BuiltinCommandSelection,
    CreateCommandRegistryOptions,
    RegisterConflictMode,
    builtin_command_group_names,
    builtin_command_groups,
    builtin_command_preset_names,
    builtin_command_presets,
    create_command_registry,
    list_builtin_commands,
    register_builtin_commands,
    register_commands,
)

__all__ = [
    "BuiltinCommandGroupName",
    "BuiltinCommandPresetName",
    "BuiltinCommandSelection",
    "CommandContext",
    "CommandHandler",
    "CommandRegistry",
    "CommandSpec",
    "CreateCommandRegistryOptions",
    "RegisterConflictMode",
    "append",
    "adapter_commands",
    "builtin_command_group_names",
    "builtin_command_groups",
    "builtin_command_preset_names",
    "builtin_command_presets",
    "calc",
    "cat",
    "cp",
    "create_command_registry",
    "data_commands",
    "diff",
    "echo",
    "fetch",
    "find",
    "fs_commands",
    "grep",
    "head",
    "help_command",
    "json_command",
    "list_builtin_commands",
    "ls",
    "memory",
    "maybe_await",
    "mkdir",
    "mv",
    "register_builtin_commands",
    "register_commands",
    "rm",
    "sed",
    "search",
    "sort",
    "stat",
    "system_commands",
    "tail",
    "text_commands",
    "tr",
    "uniq",
    "wc",
    "write",
]
