declare module 'node:assert/strict';
declare module 'node:fs';
declare module 'node:fs/promises';
declare module 'node:os';
declare module 'node:path';
declare module 'node:process';
declare module 'node:readline/promises';
declare module 'node:test';
declare module 'node:url';
